version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:Varaprasad123@db:5432/mediportal?sslmode=disable
    ports:
      - "8080:8080"  # Expose your Go app port
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Varaprasad123
      POSTGRES_DB: mediportal
    ports:
      - "5433:5432"  # Map host 5433 to container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
